# Scientific Method & Experimental Design {#sec-scientific-method-experimental-design}

Even though you might not consider yourself a "computer person" at this point you cannot get around a fundamental computer literacy and ideally having a few more advance computational tools in your tool kit in the environmental sciences^[Given the advances in instrumentation, arguable we invented big data!] - a lot of these transfer to other fields as well.

This semester we will explore various data sets using mapping/GIS tools that make data publicly available and explorable. We will also use Excel/GoogleSheets, R/posit to explore data sets in more detail.

Have an open and flexible mindset - Excel and R can have a steep learning curve and things might go wrong but once you get the hang of it, it is a very powerful tool with a wide range of applications. Many State and Federal agencies use R to summarize, analyze, and visualize their data sets and many of them have even created R packages to allow you to interact with their data.

Over the course of the semester you will be introduced to fundamental principles of scientific method and experimental design and start to built a basic tool kit of data analysis skills as well as your ability communicate your results.

By engaging with our various lab activities you will learn to

-   Outline the scientific method as an iterative process of observation, hypothesis formation, experimentation, data collection & analysis, and conclusion drawing.
-   Use spreadsheets to enter and manage data.
-   Describe the key components of experimental design to ensure conclusions are reliable.
-   Generate and interpret descriptive statistics summarizing distribution, central tendency and variability of a data set.
- Visualize and interpret results.

