# Writing a scientific report {#sec-writing-a-scientific-report}

```{r}
#| label: set-up
#| include: false

# set options
knitr::opts_chunk$set(tidy = FALSE)
options(htmltools.dir.version = FALSE)

```

## Learning Objectives {#sec-learning-objectives}

**After completing this activity, you should be able to**

-   List the four key sections of a research paper and what their central purpose is.
-   Outline the structure of a lab report.
-   Describe key components for each section of a lab report.

A scientific research paper is structured into four sections:

1.  An **introduction** of relevant background information providing context for your central question/hypothesis question and the objectives of your study.
2.  A clear description and justification of your experimental design, including the **methods** you used both to collect and analyze your data.
3.  A summary of your **results**.
4.  A clear interpretation and **discussion** of your results leading to an explicit (set of) conclusions.

In addition, a scientific publications will typically have a "fifth" component, the **Abstract** which summarizes the Introduction, Methods, Results, and Discussion/Conclusion in a single paragraph. Your will not need to include one in your lab reports for this course.

Generally, scientific research papers have an **hourglass shape**, where they start off very broad, become increasingly narrow as you describe your very specific study and then become more broad as you interpret and discuss the results in the broad context of the original research question you posed.

You will structure your lab reports in this format - don't worry, we will give you guidance, though as you progress through the semester and (hopefully) feel more confident you will increasingly become more independent and require less scaffolding.

## General Notes on scientific reports {#sec-general-notes-on-scientific-reports}

Before we dig into the actual components of a lab report, a few key pointers.

The way you structure and format your report plays a critical role in how the content is delivered. Your goal should be to produce a report that is well-organized, coherent, and the presentation of the information is clear, engaging, and enhances the understanding. This means, that you want to lower the cognitive burden of your reader, i.e. help them think by guiding them through your thought process - you want them to come to the same conclusion as you. Structure your information to help them do this and make that structuring explicit by using headers and sub-headers to make the hierarchy of information and connections obvious to them.

Here are a few things you can incorporate in terms of structure to help keep your reader engaged and following the story you are telling.

### Think of every paragraph as a container of a single thought {#sec-think-of-every-paragraph-as-a-container-of-a-single-thought}

Paragraphs are your fundamental building block. A paragraphs says one thing: Your first sentence[^f06_writing-report-1] summarizes the overall message or main points of a paragraph and functions as the logical transition from the previous paragraph. The rest of the paragraph supports, elaborates, and defends it. Effective paragraphs comprise about 150 - 250 words, much longer and you usually have more ideas creeping in, much shorter and you are likely missing a key point. A good way to proof read your paragraphs is to read it out loud to help you spot sentence fragments, run-on sentences, places where the subject and verb are mismatched.

[^f06_writing-report-1]: This is generally referred to as a topic sentence

### Structure your thinking and then your writing {#sec-structure-your-thinking-and-then-your-writing}

Remember to embrace the hour glass structure: Your introduction should start broad, then become more specific as you narrow in on your specific question. After describing your study design and completing your analysis and describing your results (this is the most specific piece of content) you start narrow with your results and then become increasingly broad in your discussion points as you put your results back into the original context of the question you asked and end with your conclusions.

Before you start writing paragraphs, create an outline to clarify your thinking and then your writing. Start with the key components, then for each section add your main points and the supporting details[^f06_writing-report-2]. At this bare bones stage you are just looking at the skeleton and so it is easier to spot anything in that paragraph that does not belong in there or needs to be in another place. Flesh out each "main point" into a topic sentence and gradually build out your supporting points into full sentences.

[^f06_writing-report-2]: You may find that some of your supporting details are actually main points and vice versa it is a lot easier to move those around at this point.

### Don't write your report linearly: {#sec-dont-write-your-report-linearly}

Start with the last statement in your introduction[^f06_writing-report-3] which summarizes your experimental design and objectives and will serve to transition between your introduction and method section.

[^f06_writing-report-3]: Think of this as a trailer previewing the remainder of a season "This season on XXX"

> In this study, we investigated \[CENTRAL QUESTION OR HYPOTHESIS\]. To do this we used \[DESCRIPTION OF HOW DATA WAS GENERATED\] to \[METRICS THAT WERE CALCULATED\].

Next, move onto your methods. Then, take the subheading of your methods and fill in the results for each section. Now that you have your results you can write the first section of your discussion[^f06_writing-report-4]. This summarizes your key findings and connects them to your hypothesis. It serves as a transition from your results to your discussion where you will interpret your results.

[^f06_writing-report-4]: Think of this as the quick summary before a tv episode "Previously, on XXX

> In this study, I investigated \[broad question asked/hypothesis tested\]. To achieve this, I \[specific data set + analysis used\]. I found that \[key results\] which \[statement about how this does or does not support your hypothesis\].

Build out your discussion, by starting with the interpretation of your results and then your discussion specific to the outcome of your experiment. Finally, widen the scope to discuss how your study fits into the broad research context. Think about your introduction and discussion as bookends framing your specific study: There is an element of them being mirror images where the key points are quite similar with the difference being that in the discussion you are revisiting key statements and questions you raised in the introduction with the specific information you have just gleaned.

Now, that you know what that broad research context is you know what themes you need to set up in your introduction. And then as a final touch, come up with a descriptive **title** for your lab report.

### Use parallel structures where possible: {#sec-use-parallel-structures-where-possible}

The hour glass structure, Introduction/Discussion as bookend with matching last intro/first discussion paragraphs are parallels that help your reader because it is easy to follow your line of thought. Additionally you can add explicit parallels to lower the cognitive burden by intentionally structuring steps/points consistently in the same way. For example, if you list three major parts in your last introduction paragraph list them in the same logical sequence you will complete them in your data analysis section, in your data analysis section use sub-headers to indicate which component you are currently completing and then summarize your results after each section (this becomes even more important when you separate methods and results into separate sections). In your first paragraph of the discussion list those key take-aways in the same sequence and then in your discussion, have the paragraphs discussing each key point in the same sequence as well.

### Don't just give the what, make sure you include the why: {#sec-dont-just-give-the-what-make-sure-you-include-the-why}

Don't just list what you are doing, always explicitly state why you are taking this step, e.g. don't say "I made a scatterplot" say "I am exploring the relationship of xx and xx using a scatterplot". An easy formulaic way to write this out is "I am going to do xxx to determine xxx". Similarly, where needed justify why this is an appropriate choice.

### Be precise and accurate {#sec-be-precise-and-accurate}

You need to make sure that your reader is understanding the exact meaning that you want to convey.

-   Use formal, written English
-   Make sure you are using correct terminology. For example, only use "significant" when you are talking about statistical results.
-   Avoid being jargon-y[^f06_writing-report-5].
-   Be specific and concrete. For example, use "for 48 hours", not "a period of time".

[^f06_writing-report-5]: Make sure people know the words you are using, for example, by defining them the first time they are used.

### Use active voice {#sec-use-active-voice}

**For this course, use the active voice when possible as this will allow you to write in a more direct and clear fashion.**

While passive voice is not grammatically incorrect, it can lead to awkward syntax and be less clear. There is some debate whether scientific reports should be written in passive voice[^f06_writing-report-6] or in passive voice[^f06_writing-report-7]. Passive voice has a sentence construction of Object-Verb-Subject which makes the object the focus of the sentence and can obscure who is acting. By contrast, active voice places an emphasis on who is acting by making the subject the focus of the sentence (Subject-Verb-Object).

[^f06_writing-report-6]: "Science happens"; this emphasizes the objectivity

[^f06_writing-report-7]: "People do science"

### Use the correct Verb Tense {#sec-use-the-correct-verb-tense}

For lab reports we use past, present, and future tenses in specific context and you should make sure you are being consistent in how you do this. You should be using the past tense when you are referring to events in the past, including results obtained in the past, and tasks you completed (methods section). You should use the present tense in the Introduction and Discussion section when you are presenting established knowledge and the implications of your results. You would only use future tense when you are talking about future steps you might take.

## Lab report components {#sec-lab-report-components}

### Title {#sec-title}

Your title should be informative and clearly state the main focus or purpose of your study. It does not need to be especially clever or thought-provoking, your focus should be on clear communication. There are typically two ways to do this, either by a stating what was done or what was found. You should consider how broad to make your title.

### Introduction {#sec-introduction}

**Your introduction should establish the context the reader needs to understand the topic.**

Think of your introduction as the funnel or top piece of an hourglass that starts off broad and become increasingly focused on the specific focus of your study.

-   Introduce the broad topic/general research question you are asking, including why this is an important question to be asking. Give a brief overview of the current state of understanding of the research question. Make sure you introduce any key terms/concepts to set up the context of a large question/scientific field or overarching theme.
-   Increasingly narrow your scope down to the specific focus of your study. Describe why your question is relevant and how it furthers the understanding of this question: Even though you cannot fully answer the big question you laid out, you can contribute to part of the answer by filling a knowledge gap or clarifying existing conflicting results.
-   Clearly state the purpose of your research, you should state what your hypothesis is, what you expect to find and why, and how you are testing this[^f06_writing-report-8].

[^f06_writing-report-8]: No details about your methods/results yet at this point, just brief "how".

You should always have at least two paragraphs. The first, sets up the broad context[^f06_writing-report-9].The last paragraph summarizes what the specific study at hand is investigating and how that will be done. It forms a “bridge” between the introduction that sets up relevant background information (why is my question important?) and the methods section which is a very detailed account of how data was acquired (experimental design), processed, and analyzed.

[^f06_writing-report-9]: For a lab report you can likely do this in a single paragraph, in a longer research paper you will likely then take several following paragraphs to flesh out relevant background information

You can use a "formula" to make sure that your introduction ends with a clear statement of the purpose of your study that summarizes your introduction.

> In this study, we investigated \[CENTRAL QUESTION OR HYPOTHESIS\]. To do this we used \[DESCRIPTION OF HOW DATA WAS GENERATED\] to \[OBJECTIVES: METRICS THAT WERE CALCULATED/WHY\].

You should always be able to make a 2-3 sentence statement summarizing what you are investigating and how you did it, it’s a good self-check that you know what you’re trying to accomplish.

**Checklist for a good introduction**

-   Am I giving just enough context for my reader to understand my research question and rationale for my hypothesis or is there a lot of unrelated information?
-   Do I explain how my study fits into the current understanding of the field and how it contributes to the overarching research question?
-   Am I clearly defining all key terms?
-   Did I include components that should actually be in my methods, results, or discussion?

Your introduction should comprise about 15-20% of your lab report.

### Methods {#sec-methods}

**Your method section should describe your study design, how you collected, processed, and analyzed the data.**

Your "Introduction Funnel" has now landed you in the most specific part of your report, where you need to describe how you conducted your study, specifically how you gathered and analyzed your data. It should be sufficiently detailed so your study could be repeated by somebody else and reproduce the same results. Make sure you strike the balance of providing necessary details and why you made specific decisions without getting lost in the weeds[^f06_writing-report-10]. It can be helpful to structure your method section with subheadings to include important components of your study, e.g.

[^f06_writing-report-10]: For example, we need to know that seedling length was measured in millimeters but we don't need to know that each seedling was removed from the petri dish, laid out on a paper towel, measured by lab partner A etc

-   Study area/Site description or Laboratory Setting/Experimental Conditions:
    -   Describe geographic location, habitat of field experiment, you may want to include a map as a figure.
    -   For controlled experiments you would include information on where the study was conducted and under what conditions.
-   Experimental design: Concisely describe how you set up your experiment in terms of sample size, replicates, what measurements where taken to produce the data set that was then analyzed.
-   Data Analysis: include how you manipulated data to obtain results, specific calculations, descriptive statistics to summarize data (what metrics you produced), statistical tests.

Remember, that your methods section should be written in paragraph form, not as a list of individual steps as you would in a protocol. Justify specific decisions you made about design where needed. You should not include a list of materials, rather you would include that information in the paragraph at the appropriate time, including specialized equipment, concentrations of chemical solutions etc.

**Checklist for a good methods section**

-   Did I provide enough details to allow study to be reproduced?
-   Did I structure my methods in easy-to-follow, logical paragraphs as opposed to a bullet list or recipe-style set of instructions?

Your methods should comprise about 10-15% of your report.

### Results {#sec-results}

**This section should present your results based the visualizations and any processing of data (e.g. descriptive and inferential statistics) you applied to analyze your data set.**

You results section should include a written description along with data visualizations in the form of tables and figures that present your results in a way that makes it easy for the reader to identify key findings[^f06_writing-report-11]. Focus on describing trends and patterns and report which findings are significant. Highlight notable results, when you mention anomalous and unexpected results make sure you pick up on those in the discussion. Remember that you should not be interpreting your data by comparing them to results from other studies, or interpreting them in the context of your research hypothesis.

[^f06_writing-report-11]: You should not include any raw data, it should always be summarized/analyzed.

Generally, you should present your results in only one format as either a table or figure that support your written descriptive narrative of your results. So for example, if you have a table with the mean +/- standard deviation of your seedling lengths you would describe your results as "Seedlings exposed to plant xx where xx mm shorter (see Table 1)". In you text you are describing the pattern, you are being specific and quantitative but you are not just listing out the information in the Table which has the exact mean values. Using the written description allows you to give context to your results ("increased", "wider", "smaller") and guide the reader through your results that you have spent a lot of time thinking about but are new to them.

While your written description alone should provide all the needed information without the figures and tables, your figures and tables should complement the text of your report. You do want to make sure that your figures and tables stand alone[^f06_writing-report-12] by giving them a descriptive figure caption comprising of a descriptive title along with any other information that is needed to understand the information being presented. Figures and Tables should be numbered, by convention captions are placed below figures and above tables. Any figure or table that you include should be referenced in your text.

[^f06_writing-report-12]: This means they should be understood without reading the entire paper

**Checklist for a good results section**

-   Have I described all my summarized data and statistical results?
-   Did I point out all the trends and patterns?
-   Did I highlight notable/anomalous results?
-   Did I report which results are significant?
-   Did I make sure not to include an interpretation or explanation of my results?

Your results should comprise about 10-15% of your lab report, figures/tables not included.

### Discussion {#sec-discussion}

**A good discussion evaluates context, acknowledges constraints, and justifies conclusions.**

Now it is time to take your specific results and broaden the scope of your report as you interpret and discuss your results. Your discussion should mirror your introduction in structure and scope, as now you start with your specific study and build your discussion back out to the broad context you set up initially.

Transition from your results section by making an explicit statement whether your results support your research question or not[^f06_writing-report-13]. A good way to do this is by reiterating the original (broad) question you asked with short description of how you specifically investigated it, your key results[^f06_writing-report-14], and then interpreting/discussing those. Similar to the last paragraph of your introduction section, you can essentially follow a fill-in-the-blank-formula, which as you become more comfortable communicating your research will sound a little less formulaic and a little bit more you[^f06_writing-report-15]:

[^f06_writing-report-13]: Remember that we generally use the terms "support" and "reject" when referring to a hypothesis not "prove" and "disprove"

[^f06_writing-report-14]: Make sure that you are making a very concise summary, not restating all of your results in detail.

[^f06_writing-report-15]: Notice how this statement is quite similar to how you ended your introduction, except now you have the results/an answer.

> In this study, I investigated \[broad question asked/hypothesis tested\]. To achieve this, I \[specific data set + analysis used\]. I found that \[key results\] which \[statement about how this does or does not support your hypothesis\].

Build on this statement to write an effective discussion that reiterates the key results and interprets them, acknowledges constraints of the study design and other possible caveats limiting clear interpretation, states clear conclusions/take-home messages, and points to results (figures or tables) as evidence thereof. In addition to ending with a clear set of conclusions you should include these four components:

-   Interpret your results and compare them to your expectations and other studies[^f06_writing-report-16]:
    -   Did your results match your predictions?
    -   Do your results support your hypothesis? How do you interpret them in that context?
    -   Why do you think you ended up with these results?
    -   Are your results consistent with similar studies/your classmates results? Different? Why?
-   Discuss constraints/limitations, inconsistencies, other possible explanations[^f06_writing-report-17]
    -   Acknowledge and discuss constraints, point out shortcomings and any caveats for how your data should be interpreted.
    -   Explain unexpected results.
    -   If results are inconsistent/ambiguous why are you confident you are interpreting them way you are?
    -   Are the other possible explanations? Other reasons of why you may have ended up with the results you did?
    -   Are there any errors, assumptions, ambiguities etc that could have impacted your results? Why you are still confident interpreting you data as you are?
    -   How might you redesign the experiment for more clear results?
-   Discuss implications of your results[^f06_writing-report-18].
    -   How do your results contribute to answering your overarching research question?
    -   Why is your study important? What do we know now that we didn't before?
-   Future steps
    -   What questions where generated?
    -   What is the next step to even better understand your overarching research question?

[^f06_writing-report-16]: In this semester we will generally keep the "compare to other studies very small, don't worry, you won't have to go on an extended literature search.

[^f06_writing-report-17]: This is still really specific to your study.

[^f06_writing-report-18]: Now you are broadening your scope to the broader context in which you asked your question

This is not a checklist or outline - think through all of the questions in the context of your experiment. Not all of them will apply. Then structure the information in a meaningful way to present to your reader.

**Checklist for a good discussion**

-   Does your discussion state whether it supports your hypothesis?
-   Did you discuss any issues with your study?
-   Did you explain how your results fit into and contribute to the broader research question?

Your discussion should comprise about 40-45% of your Lab report[^f06_writing-report-19]

[^f06_writing-report-19]: The more practice you get, the more you will find that this is the case.
